// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using leadgen.Data;

#nullable disable

namespace leadgen.Migrations
{
    [DbContext(typeof(LeadgenDbContext))]
    [Migration("20260504203233_InitialLeadgenSchema")]
    partial class InitialLeadgenSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Leadgen.Model.Entities.BusinessDnaMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Delta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mechanic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimarySurface")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SurfaceTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Villain")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessDnaMissions");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.ClarificationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BusinessDnaMissionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDnaMissionId");

                    b.ToTable("ClarificationQuestions");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.ContactChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetContactId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetContactId");

                    b.ToTable("ContactChannels");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.EvidencePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsQualificationSignal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSnippet")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlatform")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetContactId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetContactId");

                    b.ToTable("EvidencePoints");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.LeadDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdvantagePoint")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadyForOutreach")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadgenScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MissionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedApproach")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupportingEvidenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetContactId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MissionRunId");

                    b.HasIndex("TargetCompanyId");

                    b.HasIndex("TargetContactId");

                    b.ToTable("LeadDossiers");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.MissionAgentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MissionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SwarmAgentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenBudget")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionRunId");

                    b.HasIndex("SwarmAgentId");

                    b.ToTable("MissionAgentAssignments");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.MissionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BusinessDnaMissionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchRegion")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenBudget")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDnaMissionId");

                    b.HasIndex("RunCode")
                        .IsUnique();

                    b.ToTable("MissionRuns");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.SwarmAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFocus")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrentTasks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeName")
                        .IsUnique();

                    b.ToTable("SwarmAgents");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.TargetCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadquartersCity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadquartersCountry")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHeadquartersVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSignalAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MissionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationStageLabel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MissionRunId");

                    b.ToTable("TargetCompanies");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.TargetContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUsername")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDecisionMaker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpportunitySummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("XHandle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetCompanyId");

                    b.ToTable("TargetContacts");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.ClarificationQuestion", b =>
                {
                    b.HasOne("Leadgen.Model.Entities.BusinessDnaMission", "Mission")
                        .WithMany("ClarificationQuestions")
                        .HasForeignKey("BusinessDnaMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.ContactChannel", b =>
                {
                    b.HasOne("Leadgen.Model.Entities.TargetContact", "TargetContact")
                        .WithMany("ContactChannels")
                        .HasForeignKey("TargetContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetContact");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.EvidencePoint", b =>
                {
                    b.HasOne("Leadgen.Model.Entities.TargetContact", "TargetContact")
                        .WithMany("EvidencePoints")
                        .HasForeignKey("TargetContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetContact");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.LeadDossier", b =>
                {
                    b.HasOne("Leadgen.Model.Entities.MissionRun", "MissionRun")
                        .WithMany("LeadDossiers")
                        .HasForeignKey("MissionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leadgen.Model.Entities.TargetCompany", "TargetCompany")
                        .WithMany("LeadDossiers")
                        .HasForeignKey("TargetCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Leadgen.Model.Entities.TargetContact", "TargetContact")
                        .WithMany("LeadDossiers")
                        .HasForeignKey("TargetContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MissionRun");

                    b.Navigation("TargetCompany");

                    b.Navigation("TargetContact");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.MissionAgentAssignment", b =>
                {
                    b.HasOne("Leadgen.Model.Entities.MissionRun", "MissionRun")
                        .WithMany("AgentAssignments")
                        .HasForeignKey("MissionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leadgen.Model.Entities.SwarmAgent", "SwarmAgent")
                        .WithMany("MissionAssignments")
                        .HasForeignKey("SwarmAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MissionRun");

                    b.Navigation("SwarmAgent");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.MissionRun", b =>
                {
                    b.HasOne("Leadgen.Model.Entities.BusinessDnaMission", "Mission")
                        .WithMany("Runs")
                        .HasForeignKey("BusinessDnaMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.TargetCompany", b =>
                {
                    b.HasOne("Leadgen.Model.Entities.MissionRun", "MissionRun")
                        .WithMany("TargetCompanies")
                        .HasForeignKey("MissionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissionRun");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.TargetContact", b =>
                {
                    b.HasOne("Leadgen.Model.Entities.TargetCompany", "TargetCompany")
                        .WithMany("Contacts")
                        .HasForeignKey("TargetCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetCompany");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.BusinessDnaMission", b =>
                {
                    b.Navigation("ClarificationQuestions");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.MissionRun", b =>
                {
                    b.Navigation("AgentAssignments");

                    b.Navigation("LeadDossiers");

                    b.Navigation("TargetCompanies");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.SwarmAgent", b =>
                {
                    b.Navigation("MissionAssignments");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.TargetCompany", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("LeadDossiers");
                });

            modelBuilder.Entity("Leadgen.Model.Entities.TargetContact", b =>
                {
                    b.Navigation("ContactChannels");

                    b.Navigation("EvidencePoints");

                    b.Navigation("LeadDossiers");
                });
#pragma warning restore 612, 618
        }
    }
}
